#!/usr/bin/env bash
# Build ~/.claude/CLAUDE.md from personal.md + agent-ops.md.
# These rules steer Claude Code on every machine, so it shows what would change and asks
# before installing. It refuses to overwrite an installed copy that changed since the last
# install (e.g. via /memory or "add this to CLAUDE.md") and shows the diff instead.
#   ./install.sh          show the change, ask, then install
#   ./install.sh --yes    install without asking; required when there's no terminal
#   ./install.sh --force  back up an edited installed copy, then overwrite it
set -euo pipefail

repo="$(cd "$(dirname "$0")" && pwd)"
dest_dir="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
dest="$dest_dir/CLAUDE.md"
stamp="$dest_dir/.CLAUDE.md.installed-sha256"

force=false
yes=false
for arg in "$@"; do
  case "$arg" in
    --force) force=true ;;
    --yes) yes=true ;;
    *) echo "usage: $0 [--yes] [--force]" >&2; exit 2 ;;
  esac
done

sha() {
  if command -v sha256sum >/dev/null; then sha256sum; else shasum -a 256; fi | cut -d' ' -f1
}

rev="$(sed -n 's/.* rev \([0-9][0-9]*\) .*/\1/p' "$repo/agent-ops.md" | head -n1)"
commit="$(git -C "$repo" rev-parse --short HEAD 2>/dev/null || echo unknown)"
if [ -n "$(git -C "$repo" status --porcelain -- personal.md agent-ops.md 2>/dev/null)" ]; then
  commit="$commit-dirty"
fi

build() {
  cat <<EOF
<!--
GENERATED by install.sh from $repo (agent-ops rev ${rev:-?}, commit $commit).
Edit personal.md or agent-ops.md there and rerun install.sh. Edits made here
block the next install until they're folded back into the repo.
-->

EOF
  cat "$repo/personal.md"
  echo
  cat "$repo/agent-ops.md"
}

new="$(mktemp)"
trap 'rm -f "$new"' EXIT
build > "$new"
new_sha="$(sha < "$new")"

current=/dev/null
edited=false
if [ -f "$dest" ]; then
  current="$dest"
  cur_sha="$(sha < "$dest")"
  if [ "$cur_sha" = "$new_sha" ]; then
    echo "up to date: $dest"
    exit 0
  fi
  if [ "$cur_sha" != "$(cat "$stamp" 2>/dev/null || true)" ]; then
    if ! $force; then
      echo "refusing: $dest changed since the last install, or wasn't installed by this script." >&2
      echo "Lines marked '-' exist only in the installed copy. Fold them into the repo and rerun," >&2
      echo "or rerun with --force to back up the installed copy and overwrite it." >&2
      echo >&2
      diff -u "$dest" "$new" >&2 || true
      exit 1
    fi
    edited=true
  fi
fi

if ! $yes; then
  echo "Installing would make this change to $dest:" >&2
  echo >&2
  diff -u "$current" "$new" >&2 || true
  echo >&2
  if [ ! -t 0 ]; then
    echo "not installed: no terminal to ask on. Read the change above, then rerun with --yes." >&2
    exit 1
  fi
  read -r -p "Install it? [y/N] " answer
  case "$answer" in
    y|Y|yes) ;;
    *) echo "not installed" >&2; exit 1 ;;
  esac
fi

if $edited; then
  backup="$dest.bak-$(date +%Y%m%d-%H%M%S)"
  cp "$dest" "$backup"
  echo "backed up edited copy to $backup"
fi

mkdir -p "$dest_dir"
cp "$new" "$dest"
echo "$new_sha" > "$stamp"
echo "installed: $dest (agent-ops rev ${rev:-?}, commit $commit)"
