#!/usr/bin/env bash
# Build ~/.claude/CLAUDE.md from personal.md + agent-ops.md.
# Refuses to overwrite an installed copy that changed since the last install
# (e.g. via /memory or "add this to CLAUDE.md") and shows the diff instead.
#   ./install.sh          install, or refuse if the installed copy was edited
#   ./install.sh --force  back up the installed copy, then overwrite it
set -euo pipefail

repo="$(cd "$(dirname "$0")" && pwd)"
dest_dir="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
dest="$dest_dir/CLAUDE.md"
stamp="$dest_dir/.CLAUDE.md.installed-sha256"

force=false
case "${1:-}" in
  "") ;;
  --force) force=true ;;
  *) echo "usage: $0 [--force]" >&2; exit 2 ;;
esac

sha() {
  if command -v sha256sum >/dev/null; then sha256sum; else shasum -a 256; fi | cut -d' ' -f1
}

rev="$(sed -n 's/.* rev \([0-9][0-9]*\) .*/\1/p' "$repo/agent-ops.md" | head -n1)"
commit="$(git -C "$repo" rev-parse --short HEAD 2>/dev/null || echo unknown)"
if [ -n "$(git -C "$repo" status --porcelain -- personal.md agent-ops.md 2>/dev/null)" ]; then
  commit="$commit-dirty"
fi

build() {
  cat <<EOF
<!--
GENERATED by install.sh from $repo (agent-ops rev ${rev:-?}, commit $commit).
Edit personal.md or agent-ops.md there and rerun install.sh. Edits made here
block the next install until they're folded back into the repo.
-->

EOF
  cat "$repo/personal.md"
  echo
  cat "$repo/agent-ops.md"
}

new="$(mktemp)"
trap 'rm -f "$new"' EXIT
build > "$new"
new_sha="$(sha < "$new")"

if [ -f "$dest" ]; then
  cur_sha="$(sha < "$dest")"
  if [ "$cur_sha" = "$new_sha" ]; then
    echo "up to date: $dest"
    exit 0
  fi
  if [ "$cur_sha" != "$(cat "$stamp" 2>/dev/null || true)" ]; then
    if ! $force; then
      echo "refusing: $dest changed since the last install, or wasn't installed by this script." >&2
      echo "Lines marked '-' exist only in the installed copy. Fold them into the repo and rerun," >&2
      echo "or rerun with --force to back up the installed copy and overwrite it." >&2
      echo >&2
      diff -u "$dest" "$new" >&2 || true
      exit 1
    fi
    backup="$dest.bak-$(date +%Y%m%d-%H%M%S)"
    cp "$dest" "$backup"
    echo "backed up edited copy to $backup"
  fi
fi

mkdir -p "$dest_dir"
cp "$new" "$dest"
echo "$new_sha" > "$stamp"
echo "installed: $dest (agent-ops rev ${rev:-?}, commit $commit)"
